name: Triggers and concurrency

on:
    workflow_dispatch:

jobs:
    Build_Job:
        runs-on: windows-latest
        steps:
        - name: Build process
          run: echo "Building ..."

    Deploy_Job:
        needs: Build_Job
        concurrency: 
            group: production-deployment
            cancel-in-progress: false
        runs-on: windows-latest
        steps:
        - name: Deploy process
          run: echo "We are deploying now ..."

        - name: Sleep a while
          run: sleep 600s        