name: First Workflow

on: push   #Trigger

jobs:
    First_Job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo "Welcome to my First GitHub Action"
            
            - name: Checkout Repo
              uses: actions/checkout@v4 # Action must be declared with 'uses' not 'run'
              
            - name: List files
              run: ls -la

    # SecondJob:
    #     runs-on: windows-latest
    #     steps