name: Lab 1

on: push  

jobs:
    # hello-job:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Echo text
    #           run: echo "Hello, world!"
    
    build:
        runs-on: ubuntu-latest
    
        steps:
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
    
        - name: Install dependencies
          run: |
            pip install -r requirements.txt