name:  Workflow Filters and Activities

on:  
  workflow_dispatch:
#   schedule:
#     - cron: "*/59 * * * *"

#   First Event Trigger ( push )
  push:
    # Filters branches (it will trigger these branches with conditions ) and branches-ignore ( it will ignore and not trigger this workflow )
    branches:
        - main
        - '!feature/*'    # ignoring pushing to any branch name starting with feature using !    
    # branches-ignore:  
    #   - feature/*     # feature/add-music, feature/updateImages ( single slash with * )
    #   - test/**       # test/ui/index, test/checkout/payment/ ( multiple slashes with ** )

# Second Even Trigger ( pull_request)
  pull_request:
    # Activities for pull_request
    types:
      - opened
      - closed
    paths-ignore:       #  workflow will only run when a pull request that includes a change on any file other than README.md
      - README.md
    branches:
        - main          # configures your workflow to only run on pull requests that target specific branches. 

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - run: echo this workflow/job/step is executed for event type -  ${{ github.event_name }}