name: Matrix Configuration

on:
  push:
  workflow_dispatch:

jobs:
    deploy:
      strategy:
        matrix: # Under matrix strategy we gonna to define vars
          os: [ubuntu-latest, windows-latest]
          images: [hello-world, alpine]
          exclude:   # Excluding alpine image for windows runner
            - images: alpine
              os: windows-latest
          include:
            - images: amd64/alpine
              os: ubuntu-latest
      runs-on: ${{matrix.os}}
      steps:
      - name: Echo Docker Details
        run: docker info

      - name: Run Images on ${{matrix.os}}
        run: docker run ${{matrix.images}}

