name: Executing Multiple Jobs

on: push  

jobs:
    Build_Job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo "Welcome to my Third GitHub Action"
            
            - name: Checkout Repo
              uses: actions/checkout@v4 
              
            - name: Install Cowsay 
              run: sudo apt-get install cowsay -y

            - name: Execute Cowsay CMD
              run: cowsay -f dragon "Run for cover, I am a DRAGON !!" >> dragon.txt
            
            - name: Upload Dragon file  # Storing Workflow data as artifact ( Upload )
              uses: actions/upload-artifact@v3
              with:
                name: dragon_file
                path: dragon.txt

    Test_Job:
        needs: Build_Job
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4 

            - name: Download Dragon file  # Storing Workflow data as artifact ( Download )
              uses: actions/download-artifact@v3
              with:
                name: dragon_file

            - name: Test file Existance
              run: grep -i "dragon" dragon.txt

    Deploy_Job:
        needs: Test_Job # In other case, we can define multiple jobs in an array [ Test_Job, Build_Job ]
        runs-on: ubuntu-latest
        steps:
            - name: Download Dragon file  # Storing Workflow data as artifact ( Download )
              uses: actions/download-artifact@v3
              with:
                name: dragon_file

            - name: Read File
              run: cat dragon.txt     

            - name: Deploy
              run: echo "Deploying ..."
        
